language: php
php:
    - '7.1'

services:
    - mysql


# Run script
script:
    - composer install
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --env=test
    - php bin/console doctrine:fixtures:load -n --env=test
    - vendor/bin/phpunit


notifications:
    email: gebs.dev@gmail.com