<?php

namespace AppBundle\Repository;

/**
 * FortuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FortuneRepository extends \Doctrine\ORM\EntityRepository
{
}
