<?php

namespace AppBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Méthode permettant de récupérer la dernière note à réviser
     */
    public function findLastNote($id)
    {
        $query = $this->_em->createQuery('SELECT n FROM AppBundle:Note n JOIN n.categorie c JOIN c.user u WHERE u.id = :id
        AND c.aReviser = 1 AND n.dateRevision <= :now ORDER BY n.dateRevision ASC');
        $query->setMaxResults(1);
        $query->setParameter('now', new \DateTime('now'));
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    /**
     * Méthode permettant de récupérer toutes les notes à réviser
     */
    public function findAllNoteAreviser($id)
    {
        $query = $this->_em->createQuery('SELECT n FROM AppBundle:Note n JOIN n.categorie c JOIN c.user u WHERE u.id = :id
        AND c.aReviser = 1 AND n.dateRevision <= :now ORDER BY n.dateRevision ASC');
        $query->setParameter('now', new \DateTime('now'));
        $query->setParameter('id', $id);

        return $query->getResult();
    }

    public function findAllByUser($id, $term)
    {
        $query = $this->_em->createQuery('SELECT n.id, n.titre FROM AppBundle:Note n JOIN n.categorie c JOIN c.user u WHERE u.id = :id
        AND n.titre LIKE :term');
        $query->setParameter('id', $id);
        $query->setParameter('term', '%' . $term. '%');

        return $query->getResult();
    }
}
