# app/config/routing.yml

rn_user:
    resource: "@GebsUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@TwigBundle/Controller/'
    type: annotation


gebs:
    resource: '@GebsUserBundle/Controller/'
    type: annotation
