# src/AppBundle/Resources/config/services.yml

services:
    file_uploader:
        class:  AppBundle\Service\FileUploader
        arguments:
            $targetDir: '%images_directory%'


    tab_categories:
        class:  AppBundle\Service\TabCategories


    level_categorie:
        class:  AppBundle\Service\LevelCategorie
        arguments:
            - "@doctrine.orm.entity_manager"